name: 'hello world'
description: 'Lets go!'
author: 'mathias gheno <mathiasgheno@gmail.com>'

inputs:
  character:
    description: 'Futurama Character'
    default: 'dr-zoidberg'

outputs:
  quote:
    description: 'result'

runs:
  using: 'node12'
  main: 'dist/index.js'
